######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 3 10:48:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += daemon.h \
           /home/maksaw/plexydesk/extensions/widgets/twitterplugin/twitterinterface.h \
           /home/maksaw/plexydesk/extensions/widgets/twitterplugin/twitterplugin.h \
           ../extensions/widgets/twitterplugin/twitterinterface.h
SOURCES += daemon.cpp \
           main.cpp \
           /home/maksaw/plexydesk/extensions/widgets/twitterplugin/twitterplugin.cpp
